FROM python:3.10-slim

# Cambiamos el directorio de trabajo a la subcarpeta donde realmente están los archivos
WORKDIR /app/Vigilante de Red

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "bot_alertas.py"]